/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 container.glb 
Author: youssefjoukeh (https://sketchfab.com/youssefjoukeh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/container-low-poly-ea5d2e8abed648c7aaf126f846d93d9f
Title: Container (Low Poly)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ContainerModel(props) {
  const { nodes, materials } = useGLTF('./containerModel.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -2.278]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert6} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('./containerModel.glb')
